//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SkyQuery.Format.VOTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SkyQuery.Format.VOTable.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C Schema for VOTable  = Virtual Observatory Tabular Format
        ///.Version 1.0 : 15-Apr-2002
        ///.Version 1.09: 23-Jan-2004 Version 1.09
        ///.Version 1.09: 30-Jan-2004 Version 1.091
        ///.Version 1.09: 22-Mar-2004 Version 1.092
        ///.Version 1.094: 04-Jun-2004 GROUP does not contain FIELD
        ///.Version 1.1 :  10-Jun-2004 remove the complexContent
        ///--&gt;
        ///&lt;xs:schema
        ///   xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;
        ///   targetNamespace=&quot;http://www.ivoa.net/xml/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Schema_VoTable_v1_1 {
            get {
                return ResourceManager.GetString("Schema_VoTable_v1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C Schema for VOTable  = Virtual Observatory Tabular Format
        ///.Version 1.0 : 15-Apr-2002
        ///.Version 1.09: 23-Jan-2004 Version 1.09
        ///.Version 1.09: 30-Jan-2004 Version 1.091
        ///.Version 1.09: 22-Mar-2004 Version 1.092
        ///.Version 1.094: 02-Jun-2004 GROUP does not contain FIELD
        ///.Version 1.1 :  10-Jun-2004 remove the complexContent
        ///.Version 1.11: GL: 23-May-2006 remove most root elements, use name= type= iso ref= structure
        ///.Version 1.11: GL: 29-Aug-2006 review and adde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Schema_VoTable_v1_2 {
            get {
                return ResourceManager.GetString("Schema_VoTable_v1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--W3C Schema for VOTable  = Virtual Observatory Tabular Format
        ///.Version 1.0 : 15-Apr-2002
        ///.Version 1.09: 23-Jan-2004 Version 1.09
        ///.Version 1.09: 30-Jan-2004 Version 1.091
        ///.Version 1.09: 22-Mar-2004 Version 1.092
        ///.Version 1.094: 02-Jun-2004 GROUP does not contain FIELD
        ///.Version 1.1 :  10-Jun-2004 remove the complexContent
        ///.Version 1.11: GL: 23-May-2006 remove most root elements, use name= type= iso ref= structure
        ///.Version 1.11: GL: 29-Aug-2006 review and added comment [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Schema_VoTable_v1_3 {
            get {
                return ResourceManager.GetString("Schema_VoTable_v1_3", resourceCulture);
            }
        }
    }
}
