//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SkyQuery.Sql.Jobs.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConeXMatchScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConeXMatchScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SkyQuery.Sql.Jobs.Query.ConeXMatchScripts", typeof(ConeXMatchScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- *** ConeXMatchResources/BuildMatchTableIndex.sql *** ---
        ///
        ///CREATE INDEX [$indexname]
        ///ON [$tablename] ( ZoneID, Ra )
        ///INCLUDE 
        ///(
        ///	[Dec], [Cx], [Cy], [Cz]
        ///	[$columnlist]
        ///).
        /// </summary>
        internal static string BuildMatchTableIndex {
            get {
                return ResourceManager.GetString("BuildMatchTableIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- *** ConeXMatchResources/ComputeSearchRadius.sql *** ---
        ///
        ///DECLARE @r dbo.Region = @region;
        ///
        ///WITH __t AS
        ///(
        ///[$query]
        ///)
        ///SELECT CONVERT(float, MAX([radius]))	-- radius in arc sec
        ///FROM __t.
        /// </summary>
        internal static string ComputeSearchRadius {
            get {
                return ResourceManager.GetString("ComputeSearchRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- *** ConeXMatchResources/CreateMatchTable.sql *** ---
        ///
        ///CREATE TABLE [$tablename]
        ///(
        ///	   [MatchID] [bigint] NOT NULL IDENTITY ([$idseed], 1),
        ///	   [RA] [float],
        ///	   [Dec] [float],
        ///	   [Cx] [float],
        ///	   [Cy] [float],
        ///	   [Cz] [float],
        ///	   [ZoneID] [int],
        ///	   [Radius] [float]
        ///	   [$columnlist]
        ///)
        ///
        ///ALTER TABLE [$tablename] ADD CONSTRAINT [$indexname] PRIMARY KEY ( [MatchID] ).
        /// </summary>
        internal static string CreateMatchTable {
            get {
                return ResourceManager.GetString("CreateMatchTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- *** ConeXMatchResources/PopulateMatchTable.sql *** ---
        ///
        ///WITH 
        ///__t1 AS
        ///(
        ///[$query1]
        ///),
        ///__t2 AS
        ///(
        ///[$query2]
        ///),
        ///__match AS
        ///(
        ///	SELECT 
        ///		point.GetAngleXyz(
        ///			__t1.[Cx], __t1.[Cy], __t1.[Cz], 
        ///			__t2.[Cx], __t2.[Cy], __t2.[Cz]) * 60.0 __arc,
        ///		__t1.[RA], __t1.[Dec],
        ///		__t1.[Cx], __t1.[Cy], __t1.[Cz],
        ///		__t1.[radius]
        ///		[$columnlist1]
        ///	FROM [$pairtable] AS __pair
        ///	INNER JOIN __t1 ON [$tablejoin1]
        ///	INNER JOIN __t2 ON [$tablejoin2]
        ///)
        ///INSERT [$matchtable] WITH (TABLOCKX)
        ///	([RA], [Dec], [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PopulateMatchTable {
            get {
                return ResourceManager.GetString("PopulateMatchTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT [$zoneid] AS [ZoneID],
        ///	       [$ra] AS [RA],
        ///	       [$dec] AS [Dec],
        ///	       [$cx] AS [Cx],
        ///	       [$cy] AS [Cy],
        ///	       [$cz] AS [Cz],
        ///	       [$htmid] AS [HtmID],
        ///		   [$radius] AS [radius]
        ///	       [$columnlist]
        ///	FROM [$tablename]
        ///	[$where].
        /// </summary>
        internal static string SelectAugmentedTable {
            get {
                return ResourceManager.GetString("SelectAugmentedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT [$zoneid] AS [ZoneID],
        ///	       [$ra] AS [RA],
        ///	       [$dec] AS [Dec],
        ///	       [$cx] AS [Cx],
        ///	       [$cy] AS [Cy],
        ///	       [$cz] AS [Cz],
        ///	       [$htmid] AS [HtmID],
        ///		   [$radius] AS [radius]
        ///	       [$columnlist]
        ///	FROM htm.Cover(@r) __htm
        ///	INNER LOOP JOIN [$tablename]
        ///		ON [$htmid] BETWEEN __htm.htmIDStart AND __htm.htmIDEnd AND __htm.partial = 0
        ///	[$where_inner]
        ///
        ///	UNION ALL
        ///
        ///	SELECT [$zoneid] AS [ZoneID],
        ///	       [$ra] AS [RA],
        ///	       [$dec] AS [Dec],
        ///	       [$cx] AS [Cx],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAugmentedTableHtm {
            get {
                return ResourceManager.GetString("SelectAugmentedTableHtm", resourceCulture);
            }
        }
    }
}
