ALTER TABLE PhotoObjAll_01 DROP CONSTRAINT CK_PhotoObjAll_01

ALTER TABLE PhotoObjAll_01 ADD CONSTRAINT CK_PhotoObjAll_01
CHECK (objid < 1237651735200924423)

ALTER TABLE [dbo].[PhotoObjAll]
SWITCH PARTITION 1 TO PhotoObjAll_01



---


SWITCH


ALTER TABLE [dbo].PhotoObjAll_01
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 1

ALTER TABLE [dbo].PhotoObjAll_02
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 2

ALTER TABLE [dbo].PhotoObjAll_03
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 3

ALTER TABLE [dbo].PhotoObjAll_04
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 4



ALTER TABLE [dbo].PhotoObjAll_05
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 5

ALTER TABLE [dbo].PhotoObjAll_06
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 6

ALTER TABLE [dbo].PhotoObjAll_07
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 7

ALTER TABLE [dbo].PhotoObjAll_08
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 8

ALTER TABLE [dbo].PhotoObjAll_09
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 9

ALTER TABLE [dbo].PhotoObjAll_10
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 10

ALTER TABLE [dbo].PhotoObjAll_11
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 11

ALTER TABLE [dbo].PhotoObjAll_12
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 12

ALTER TABLE [dbo].PhotoObjAll_13
SWITCH PARTITION 1 TO PhotoObjAll PARTITION 13



SELECT COUNT(*) FROM PhotoObjAll