//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SkyQuery.Jobs.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SkyQuery.Jobs.Query.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link table created and populated for step {0} on partition {1} in {2} sec. The number of records affected is {3}..
        /// </summary>
        internal static string LinkTableCreated {
            get {
                return ResourceManager.GetString("LinkTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match table created for step {0} on partition {1} in {2} sec for table {3}. The number of records affected is {4}..
        /// </summary>
        internal static string MatchTableCreated {
            get {
                return ResourceManager.GetString("MatchTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone table created for step {0} on partition {1} in {2} sec for table {3}. The number of records affected is {4}..
        /// </summary>
        internal static string PairTableCreated {
            get {
                return ResourceManager.GetString("PairTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search radius computed for step {0} on partition {1} in {2} sec. The search radius is {3} degrees which is equivalent to {4} zones..
        /// </summary>
        internal static string SearchRadiusComputed {
            get {
                return ResourceManager.GetString("SearchRadiusComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMatch job identified {0} tables, using the {1} zone algorithm..
        /// </summary>
        internal static string XMatchInterpreted {
            get {
                return ResourceManager.GetString("XMatchInterpreted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated {0} xmatch steps..
        /// </summary>
        internal static string XMatchStepsGenerated {
            get {
                return ResourceManager.GetString("XMatchStepsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified xmatch table {0}..
        /// </summary>
        internal static string XMatchTableIdentified {
            get {
                return ResourceManager.GetString("XMatchTableIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZoneDef table created and populated for step {0} on partition {1} in {2} sec..
        /// </summary>
        internal static string ZoneDefTableCreated {
            get {
                return ResourceManager.GetString("ZoneDefTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone table created for step {0} on partition {1} in {2} sec for table {3}. The number of records affected is {4}..
        /// </summary>
        internal static string ZoneTableCreated {
            get {
                return ResourceManager.GetString("ZoneTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-the-fly zone table generation is necessary for table {0}. Reason: {1}..
        /// </summary>
        internal static string ZoneTableNecessary {
            get {
                return ResourceManager.GetString("ZoneTableNecessary", resourceCulture);
            }
        }
    }
}
