//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SkyQuery.Jobs.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegionScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegionScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SkyQuery.Jobs.Query.RegionScripts", typeof(RegionScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- *** RegionResources/TableStatistics.sql *** ---
        ///
        ///-- Generate HTM ranges
        ///
        ///DECLARE @r dbo.RegionUdt = @region
        ///
        ///CREATE TABLE [$htm]
        ///(
        ///	htmIDStart bigint NOT NULL,
        ///	htmIDEnd bigint NOT NULL
        ///);
        ///
        ///INSERT [$htm] WITH(TABLOCKX)
        ///SELECT htmIDStart, htmIDEnd
        ///FROM htm.Cover(@region) AS htm;
        ///
        ///-- Compute statistics
        ///
        ///CREATE TABLE [$temptable]
        ///(
        ///	[rn] bigint PRIMARY KEY,
        ///	[key] [$keytype]
        ///);
        ///
        ///INSERT [$temptable] WITH(TABLOCKX)
        ///SELECT ROW_NUMBER() OVER (ORDER BY [$keycol]), [$keycol]
        ///FROM [$table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStatistics {
            get {
                return ResourceManager.GetString("TableStatistics", resourceCulture);
            }
        }
    }
}
