-- SUBSAMPLING TABLE 'PhotoObj' ---

 -- Insert subset into destination table
 INSERT [SkyNode_RC3_Mini].[dbo].[PhotoObj] WITH (TABLOCKX)
    ([name], [aliases], [PGC_name], [ra], [dec], [good_position], [galactic_l], [galactic_b], [superGalactic_l], [superGalactic_b], [PosAngle], [rc2_type], [rc2_typeSource], [T_type], [T_typeErr], [LC_rc2], [LC_rc2Err], [n_L], [B_T], [B_TErr], [B_Tsource], [B_T0], [M_B], [M_BErr], [M_FIR], [M_21cm], [M_21cmErr], [BV_T], [BV_TErr], [BV_T0], [BV_e], [BV_eErr], [UB_T], [UB_TErr], [UB_T0], [UB_e], [UB_eErr], [lgD_25], [lgD_25Err], [lgD_0], [lgR_25], [lgR_25Err], [logA_e], [logA_eErr], [m_e], [m_eErr], [m_25], [m_25Err], [A_B], [A_HI_self], [A_B_int], [W_20], [W_20Err], [W_50], [W_50Err], [HI], [V_21cm], [V_21cmErr], [V_opt], [V_optErr], [V_GSR], [V_3K], [objId], [htmid], [cx], [cy], [cz])
 SELECT sourcetablealias.[name], sourcetablealias.[aliases], sourcetablealias.[PGC_name], sourcetablealias.[ra], sourcetablealias.[dec], sourcetablealias.[good_position], sourcetablealias.[galactic_l], sourcetablealias.[galactic_b], sourcetablealias.[superGalactic_l], sourcetablealias.[superGalactic_b], sourcetablealias.[PosAngle], sourcetablealias.[rc2_type], sourcetablealias.[rc2_typeSource], sourcetablealias.[T_type], sourcetablealias.[T_typeErr], sourcetablealias.[LC_rc2], sourcetablealias.[LC_rc2Err], sourcetablealias.[n_L], sourcetablealias.[B_T], sourcetablealias.[B_TErr], sourcetablealias.[B_Tsource], sourcetablealias.[B_T0], sourcetablealias.[M_B], sourcetablealias.[M_BErr], sourcetablealias.[M_FIR], sourcetablealias.[M_21cm], sourcetablealias.[M_21cmErr], sourcetablealias.[BV_T], sourcetablealias.[BV_TErr], sourcetablealias.[BV_T0], sourcetablealias.[BV_e], sourcetablealias.[BV_eErr], sourcetablealias.[UB_T], sourcetablealias.[UB_TErr], sourcetablealias.[UB_T0], sourcetablealias.[UB_e], sourcetablealias.[UB_eErr], sourcetablealias.[lgD_25], sourcetablealias.[lgD_25Err], sourcetablealias.[lgD_0], sourcetablealias.[lgR_25], sourcetablealias.[lgR_25Err], sourcetablealias.[logA_e], sourcetablealias.[logA_eErr], sourcetablealias.[m_e], sourcetablealias.[m_eErr], sourcetablealias.[m_25], sourcetablealias.[m_25Err], sourcetablealias.[A_B], sourcetablealias.[A_HI_self], sourcetablealias.[A_B_int], sourcetablealias.[W_20], sourcetablealias.[W_20Err], sourcetablealias.[W_50], sourcetablealias.[W_50Err], sourcetablealias.[HI], sourcetablealias.[V_21cm], sourcetablealias.[V_21cmErr], sourcetablealias.[V_opt], sourcetablealias.[V_optErr], sourcetablealias.[V_GSR], sourcetablealias.[V_3K], sourcetablealias.[objId], sourcetablealias.[htmid], sourcetablealias.[cx], sourcetablealias.[cy], sourcetablealias.[cz]
 FROM   [SkyNode_RC3].[dbo].[PhotoObj] sourcetablealias WITH (NOLOCK)
	;
 

GO

